name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: mariadb
        ports:
          - 3306:3306 # local : docker port
        env:
          MYSQL_ROOT_PASSWORD: 221031
          MYSQL_DATABASE: commerce
          MYSQL_USER: calaf
          MYSQL_PASSWORD: 221031
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Start Docker
      run: sudo service docker start
    - name: Wait for Database to be Ready
      run: |
        dockerize -wait tcp://localhost:3306 -timeout 1m
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
