name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: mariadb
        ports:
          - 3306:3306
        env:
          DB_HOST: localhost
          DB_PORT: 3306
          DB_NAME: commerce
          DB_USERNAME: calaf
          DB_PASSWORD: 221031
          MARIADB_ROOT_PASSWORD : 221031
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Start Docker
      run: sudo service docker start
    - name: Wait for Database to be Ready
      run: |
        while ! docker run --rm --network host mariadb mysqladmin ping -h localhost --silent; do sleep 1; done
    - name: Build with Gradle
      run: ./gradlew build
