name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: mariadb
        ports:
          - 3306:3306 # local : docker port
        env:
          MARIADB_ROOT_PASSWORD: 221031
          DB_PORT: 3306
          DB_NAME: commerce
          DB_USERNAME: calaf
          DB_PASSWORD: 221031

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # application.properties 파일 생성
      - name: Make application.properties
        run: |
          cd ./src/main/resources
          touch ./application.properties
          
          echo "${{ secrets.DATABASE_PROPERTIES }}" >> ./application.properties
        shell: bash

      - name: Start Docker
        run: sudo service docker start
      - name: Wait for Database to be Ready
        run: |
          while ! nc -z localhost 3306; do sleep 1; done
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
